In [100]:
import pandas as pd

In [101]:
data=pd.read_excel(r"C:\Users\lenovo\Downloads\googleplaystore.xlsx")

In [102]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [103]:
data.shape

(10841, 13)

In [104]:
data.Size

0                       19M
1                       14M
2                      8.7M
3                       25M
4                      2.8M
                ...
10836                   53M
10837                  3.6M
10838                  9.5M
10839    Varies with device
10840                   19M
Name: Size, Length: 10841, dtype: object

In [105]:
data.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [106]:
data.sample(50)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5989,PMHNP-BC Pocket Prep,MEDICAL,4.4,112,13M,"1,000+",Free,0,Everyone,Medical,"July 12, 2018",4.5.2,4.4 and up
2453,Smartshading AI,MEDICAL,NaN,0,10M,10+,Free,0,Everyone,Medical,"June 21, 2018",1,4.1 and up
10640,Florida HSMV Driver License,FAMILY,3.9,14,11M,"1,000+",Free,0,Everyone,Education,"January 13, 2015",1.3,4.0 and up
6114,Bf Light,BUSINESS,NaN,6,11M,"1,000+",Free,0,Everyone,Business,"February 9, 2017",1,4.1 and up
7363,Sermon on Proverbs CH Spurgeon,GAME,4.8,35,3.1M,"10,000+",Free,0,Everyone,Trivia,"July 29, 2016",1.0.0,4.0 and up
9186,Epson iProjection,PRODUCTIVITY,3.5,3930,18M,"1,000,000+",Free,0,Everyone,Productivity,"March 22, 2018",3.0.0,4.0 and up
7137,CB Pay,FINANCE,4.5,198,11M,"10,000+",Free,0,Everyone,Finance,"July 9, 2018",1.8.0,4.4 and up
8518,Download Manager,TOOLS,3.8,79132,2.2M,"10,000,000+",Free,0,Everyone,Tools,"January 3, 2018",1.1.6,2.3 and up
3333,Speedtest by Ookla,TOOLS,4.4,1028794,Varies with device,"100,000,000+",Free,0,Everyone,Tools,"July 19, 2018",Varies with device,Varies with device
3783,Reuters News,NEWS_AND_MAGAZINES,4.3,13169,25M,"1,000,000+",Free,0,Everyone 10+,News & Magazines,"June 6, 2018",3.4.4,4.1 and up
1294,Recipes for hair and face tried,HEALTH_AND_FITNESS,4.5,1203,6.5M,"500,000+",Free,0,Everyone,Health & Fitness,"October 16, 2016",1.2,2.3.3 and up
2394,e-Anatomy,MEDICAL,4.0,1545,74M,"100,000+",Free,0,Everyone,Medical,"July 30, 2018",4.8.2,4.0.3 and up
1154,BBVA Compass Banking,FINANCE,4.3,5905,50M,"500,000+",Free,0,Everyone,Finance,"July 27, 2018",6.0.2,4.4 and up
10540,Ray Financial Calculator Pro,FINANCE,4.0,67,2.4M,"10,000+",Paid,$2.99,Everyone,Finance,"July 3, 2017",4,3.2 and up
9886,taxi.eu,TRAVEL_AND_LOCAL,4.1,1865,22M,"100,000+",Free,0,Everyone,Travel & Local,"June 28, 2018",10.7.1388,4.4 and up
1364,GeocachingÂ®,HEALTH_AND_FITNESS,4.1,62616,Varies with device,"5,000,000+",Free,0,Teen,Health & Fitness,"August 2, 2018",Varies with device,Varies with device
7929,Firefighters First CU,FINANCE,4.8,495,12M,"5,000+",Free,0,Everyone,Finance,"May 1, 2018",5.7.1.0,5.0 and up
9062,DX Simulation for X-aid Dx Belt,FAMILY,4.0,35,48M,"5,000+",Free,0,Everyone,Simulation,"August 4, 2018",1.6,4.1 and up
6588,iFORA BP,MEDICAL,3.4,18,45M,"1,000+",Free,0,Everyone,Medical,"June 5, 2018",1.2.4,2.3.3 and up
6177,BLOOD & GLORY: IMMORTALS,GAME,4.3,101762,11M,"1,000,000+",Free,0,Teen,Action,"June 11, 2015",2.0.0,3.0 and up
5899,Oxford A-Z of English Usage,BOOKS_AND_REFERENCE,4.0,5300,11M,"1,000,000+",Free,0,Everyone,Books & Reference,"November 28, 2017",9.1.284,4.1 and up
7008,Valentines love color by number-Pixel art colo...,FAMILY,4.4,767,18M,"100,000+",Free,0,Everyone,Entertainment,"February 23, 2018",1.1,4.1 and up
735,Learn English from Persian: Persian to English,EDUCATION,4.3,423,21M,"100,000+",Free,0,Everyone,Education,"April 3, 2018",6,4.0.3 and up
9163,Asphalt Xtreme: Rally Racing,GAME,4.5,567984,39M,"10,000,000+",Free,0,Everyone,Racing,"July 16, 2018",1.7.3b,4.0.3 and up
2220,DisneyNOW â€“ TV Shows & Games,FAMILY,4.3,82471,Varies with device,"5,000,000+",Free,0,Everyone,Entertainment;Music & Video,"July 5, 2018",Varies with device,4.4 and up
8427,Castle Defense : Invasion,FAMILY,4.2,1484,41M,"100,000+",Free,0,Everyone,Strategy,"July 15, 2018",1.2.1,4.0.3 and up
9029,Ham DX Cluster & Spots Finder,COMMUNICATION,4.5,115,2.8M,"5,000+",Free,0,Everyone,Communication,"July 15, 2016",1.4.4,4.1 and up
1879,Clash of Clans,GAME,4.6,44893888,98M,"100,000,000+",Free,0,Everyone 10+,Strategy,"July 15, 2018",10.322.16,4.1 and up
1832,Clue,GAME,4.6,19922,35M,"100,000+",Paid,$1.99,Everyone 10+,Board,"July 30, 2018",2.2.5,5.0 and up
9124,Agent HQ for The Division,FAMILY,4.1,1060,2.5M,"100,000+",Free,0,Everyone,Entertainment,"February 17, 2018",0.35,4.0.3 and up
2872,"Candy Camera - selfie, beauty camera, photo ed...",PHOTOGRAPHY,4.4,3368649,Varies with device,"100,000,000+",Free,0,Everyone,Photography,"July 16, 2018",4.47,4.0.3 and up
8266,DC Universe Online Map,TOOLS,4.1,1186,6.4M,"50,000+",Free,0,Unrated,Tools,"February 27, 2012",1.3,2.3.3 and up
8870,PAY DT,BUSINESS,NaN,0,5.3M,1+,Free,0,Everyone,Business,"February 6, 2018",1.1.0,4.0 and up
10035,Deus Ex GO,FAMILY,4.5,9699,23M,"100,000+",Paid,$0.99,Teen,Puzzle,"July 23, 2018",2.1.111374,4.2 and up
8860,Bloons TD 5,FAMILY,4.6,190086,94M,"1,000,000+",Paid,$2.99,Everyone,Strategy,"July 13, 2018",3.16,2.3.3 and up
3497,7 Weeks - Habit & Goal Tracker,PRODUCTIVITY,4.4,6011,4.3M,"500,000+",Free,0,Everyone,Productivity,"December 19, 2015",3.2.1,4.1 and up
1997,1LINE â€“ One Line with One Touch,GAME,4.6,214878,10M,"10,000,000+",Free,0,Everyone,Board,"August 3, 2018",2.0.4,4.1 and up
1339,Simply Yoga - Fitness Trainer for Workouts & P...,HEALTH_AND_FITNESS,4.1,6826,Varies with device,"1,000,000+",Free,0,Everyone,Health & Fitness,"June 14, 2018",Varies with device,Varies with device
2497,LactMed,MEDICAL,4.3,573,2.0M,"100,000+",Free,0,Everyone,Medical,"June 1, 2017",3.1,3.0 and up
2325,Ovia Parenting & Baby Development Tracker,MEDICAL,4.7,6185,38M,"100,000+",Free,0,Everyone,Medical,"August 3, 2018",1.2.0,4.3 and up
6032,"Youboox - Livres, BD et magazines",BOOKS_AND_REFERENCE,3.7,4071,Varies with device,"500,000+",Free,0,Teen,Books & Reference,"April 3, 2018",Varies with device,Varies with device
7999,Morse Decoder for Ham Radio,COMMUNICATION,3.7,166,2.0M,"5,000+",Paid,$4.99,Everyone,Communication,"March 14, 2017",1.52,2.3 and up
9873,Flag Of European Union LWP,PERSONALIZATION,4.3,88,4.2M,"1,000+",Free,0,Everyone,Personalization,"January 24, 2018",7,4.0.3 and up
7421,The Grand Way,GAME,3.9,1995,92M,"500,000+",Free,0,Teen,Action,"July 3, 2018",1.9,4.1 and up
1540,Sad hair without net,LIBRARIES_AND_DEMO,NaN,20,2.1M,"5,000+",Free,0,Everyone,Libraries & Demo,"March 26, 2018",1,2.3 and up
1757,slither.io,GAME,4.4,5234810,Varies with device,"100,000,000+",Free,0,Everyone,Action,"November 14, 2017",Varies with device,2.3 and up
9990,EW Manager,BUSINESS,NaN,0,4.4M,10+,Free,0,Everyone,Business,"February 20, 2018",1.0.0,4.1 and up
2441,PCOS Guide - Fight PCOS naturally,MEDICAL,NaN,0,5.1M,100+,Free,0,Everyone,Medical,"August 4, 2018",1,5.0 and up
2124,DC Super Hero Girlsâ„¢,FAMILY,4.3,43060,95M,"5,000,000+",Free,0,Everyone,Action;Action & Adventure,"June 29, 2018",2.8.0,4.0 and up
4943,Ad Detect Plugin - Handy Tool,PRODUCTIVITY,3.8,5107,1.4M,"500,000+",Free,0,Everyone,Productivity,"December 28, 2015",1.6.3,2.3 and up

In [107]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [108]:
data.describe().T

         count      mean       std  min  25%  50%  75%   max
Rating  9367.0  4.193338  0.537431  1.0  4.0  4.3  4.5  19.0

In [109]:
data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
App,10840,9659,ROBLOX,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,10841,34,FAMILY,1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rating,9367.0,NaN,NaN,NaN,4.193338,0.537431,1.0,4.0,4.3,4.5,19.0
Reviews,10841.0,6002.0,0.0,596.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,10841,462,Varies with device,1695,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Installs,10841,22,"1,000,000+",1579,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type,10840,3,Free,10039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price,10841.0,93.0,0.0,10040.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Content Rating,10840,6,Everyone,8714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Genres,10841,120,Tools,842,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last Updated,10841,1378,"August 3, 2018",326,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Current Ver,10833,2784,Varies with device,1459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Android Ver,10838,33,4.1 and up,2451,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
data[data.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

In [111]:
data['Reviews'].head(7)

0       159
1       967
2     87510
3    215644
4       967
5       167
6       178
Name: Reviews, dtype: object

In [112]:
data['Reviews'].shape

(10841,)

In [113]:
data['Reviews'].dtype

dtype('O')

In [114]:
data['Reviews'].str.isnumeric()

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
10836    NaN
10837    NaN
10838    NaN
10839    NaN
10840    NaN
Name: Reviews, Length: 10841, dtype: object

In [115]:
data[data['Reviews'].str.isnumeric()]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [116]:
data[~data['Reviews'].astype(str).str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [117]:
data_copy=data.copy()

In [118]:
data_copy=data_copy.drop(data_copy.index[10472])

In [119]:
data_copy.shape

(10840, 13)

In [120]:
data_copy['Reviews'].dtype

dtype('O')

In [121]:
data_copy['Reviews']=data_copy['Reviews'].astype('int')

In [122]:
data_copy['Reviews'].dtype

dtype('int64')

In [123]:
data_copy['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [124]:
data_copy['Size']=data_copy['Size'].str.replace("M","000")

In [125]:
data_copy['Size']=data_copy['Size'].str.replace("k","")

In [126]:
import numpy as np
data_copy['Size']=data_copy['Size'].str.replace("Varies with device",str(np.nan))

In [127]:
data_copy["Size"].unique()

array(['19000', '14000', '8.7000', '25000', '2.8000', '5.6000', '29000',
       '33000', '3.1000', '28000', '12000', '20000', '21000', '37000',
       '2.7000', '5.5000', '17000', '39000', '31000', '4.2000', '7.0000',
       '23000', '6.0000', '6.1000', '4.6000', '9.2000', '5.2000', '11000',
       '24000', 'nan', '9.4000', '15000', '10000', '1.2000', '26000',
       '8.0000', '7.9000', '56000', '57000', '35000', '54000', '201',
       '3.6000', '5.7000', '8.6000', '2.4000', '27000', '2.5000', '16000',
       '3.4000', '8.9000', '3.9000', '2.9000', '38000', '32000', '5.4000',
       '18000', '1.1000', '2.2000', '4.5000', '9.8000', '52000', '9.0000',
       '6.7000', '30000', '2.6000', '7.1000', '3.7000', '22000', '7.4000',
       '6.4000', '3.2000', '8.2000', '9.9000', '4.9000', '9.5000',
       '5.0000', '5.9000', '13000', '73000', '6.8000', '3.5000', '4.0000',
       '2.3000', '7.2000', '2.1000', '42000', '7.3000', '9.1000', '55000',
       '23', '6.5000', '1.5000', '7.5000', '51000', '41000', '48000',
       '8.5000', '46000', '8.3000', '4.3000', '4.7000', '3.3000', '40000',
       '7.8000', '8.8000', '6.6000', '5.1000', '61000', '66000', '79',
       '8.4000', '118', '44000', '695', '1.6000', '6.2000', '18', '53000',
       '1.4000', '3.0000', '5.8000', '3.8000', '9.6000', '45000', '63000',
       '49000', '77000', '4.4000', '4.8000', '70000', '6.9000', '9.3000',
       '10.0000', '8.1000', '36000', '84000', '97000', '2.0000', '1.9000',
       '1.8000', '5.3000', '47000', '556', '526', '76000', '7.6000',
       '59000', '9.7000', '78000', '72000', '43000', '7.7000', '6.3000',
       '334', '34000', '93000', '65000', '79000', '100000', '58000',
       '50000', '68000', '64000', '67000', '60000', '94000', '232',
       '99000', '624', '95000', '8.5', '41', '292', '11', '80000',
       '1.7000', '74000', '62000', '69000', '75000', '98000', '85000',
       '82000', '96000', '87000', '71000', '86000', '91000', '81000',
       '92000', '83000', '88000', '704', '862', '899', '378', '266',
       '375', '1.3000', '975', '980', '4.1000', '89000', '696', '544',
       '525', '920', '779', '853', '720', '713', '772', '318', '58',
       '241', '196', '857', '51', '953', '865', '251', '930', '540',
       '313', '746', '203', '26', '314', '239', '371', '220', '730',
       '756', '91', '293', '17', '74', '14', '317', '78', '924', '902',
       '818', '81', '939', '169', '45', '475', '965', '90000', '545',
       '61', '283', '655', '714', '93', '872', '121', '322', '1.0000',
       '976', '172', '238', '549', '206', '954', '444', '717', '210',
       '609', '308', '705', '306', '904', '473', '175', '350', '383',
       '454', '421', '70', '812', '442', '842', '417', '412', '459',
       '478', '335', '782', '721', '430', '429', '192', '200', '460',
       '728', '496', '816', '414', '506', '887', '613', '243', '569',
       '778', '683', '592', '319', '186', '840', '647', '191', '373',
       '437', '598', '716', '585', '982', '222', '219', '55', '948',
       '323', '691', '511', '951', '963', '25', '554', '351', '27', '82',
       '208', '913', '514', '551', '29', '103', '898', '743', '116',
       '153', '209', '353', '499', '173', '597', '809', '122', '411',
       '400', '801', '787', '237', '50', '643', '986', '97', '516', '837',
       '780', '961', '269', '20', '498', '600', '749', '642', '881', '72',
       '656', '601', '221', '228', '108', '940', '176', '33', '663', '34',
       '942', '259', '164', '458', '245', '629', '28', '288', '775',
       '785', '636', '916', '994', '309', '485', '914', '903', '608',
       '500', '54', '562', '847', '957', '688', '811', '270', '48', '329',
       '523', '921', '874', '981', '784', '280', '24', '518', '754',
       '892', '154', '860', '364', '387', '626', '161', '879', '39',
       '970', '170', '141', '160', '144', '143', '190', '376', '193',
       '246', '73', '658', '992', '253', '420', '404', '470', '226',
       '240', '89', '234', '257', '861', '467', '157', '44', '676', '67',
       '552', '885', '1020', '582', '619'], dtype=object)

In [128]:
data_copy["Size"]=data_copy["Size"].astype("float")

In [129]:
data['Size'].head(10)

0     19M
1     14M
2    8.7M
3     25M
4    2.8M
5    5.6M
6     19M
7     29M
8     33M
9    3.1M
Name: Size, dtype: object

In [130]:
char_to_remove=["+","$",","]
col_to_clean=["Installs","Price"]
for item in char_to_remove:
    for col in col_to_clean:
        data_copy[col]=data_copy[col].str.replace(item,"")

In [131]:
data_copy

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,NaN,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,NaN,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,NaN,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,NaN,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,NaN,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53000.0,5000,Free,NaN,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,NaN,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5,1000,Free,NaN,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,NaN,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19000.0,10000000,Free,NaN,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [132]:
data_copy['Size'].head()

0    19000.0
1    14000.0
2        8.7
3    25000.0
4        2.8
Name: Size, dtype: float64

In [133]:
for i in data_copy['Size']:
    if i<10:
        data_copy["Size"]=data_copy['Size'].replace(i,i*1000)

In [134]:
data_copy['Size'].head()

0    19000.0
1    14000.0
2     8700.0
3    25000.0
4     2800.0
Name: Size, dtype: float64

In [135]:
data_copy['Size']/1000

0        19.0
1        14.0
2         8.7
3        25.0
4         2.8
         ...
10836    53.0
10837     3.6
10838     9.5
10839     NaN
10840    19.0
Name: Size, Length: 10840, dtype: float64

In [136]:
data_copy

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,NaN,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,NaN,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8700.0,5000000,Free,NaN,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,NaN,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,100000,Free,NaN,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53000.0,5000,Free,NaN,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3600.0,100,Free,NaN,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9500.0,1000,Free,NaN,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,NaN,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19000.0,10000000,Free,NaN,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [137]:
data_copy['Installs']

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs, Length: 10840, dtype: object

In [138]:
data_copy['Installs'].unique()

array(['10000', '500000', '5000000', '50000000', '100000', '50000',
       '1000000', '10000000', '5000', '100000000', '1000000000', '1000',
       '500000000', '50', '100', '500', '10', '1', '5', '0', nan],
      dtype=object)

In [139]:
# To find rows where Installs column has NaN
data_copy[data_copy['Installs'].isna()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9148,Command & Conquer: Rivals,FAMILY,NaN,0,NaN,NaN,NaN,NaN,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device

In [140]:
data_copy = data_copy.dropna(subset=['Installs'])

In [141]:
data_copy['Installs']=data_copy['Installs'].astype("int")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12864\2737002837.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy['Installs']=data_copy['Installs'].astype("int")

In [142]:
data_copy['Price']=data_copy['Price'].astype("float")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12864\3519672648.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy['Price']=data_copy['Price'].astype("float")

In [143]:
data_copy["Last Updated"]=pd.to_datetime(data_copy["Last Updated"])

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12864\143087510.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy["Last Updated"]=pd.to_datetime(data_copy["Last Updated"])

In [144]:
data_copy['Android Ver']=data_copy['Android Ver'].str.replace("and up","")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12864\3694098092.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy['Android Ver']=data_copy['Android Ver'].str.replace("and up","")

In [145]:
data_copy['Android Ver']=data_copy['Android Ver'].str.replace("Varies with device","NaN")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12864\420008162.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy['Android Ver']=data_copy['Android Ver'].str.replace("Varies with device","NaN")

In [146]:
data_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10839 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10838 non-null  object
 1   Category        10839 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10839 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10839 non-null  int64
 6   Type            10839 non-null  object
 7   Price           800 non-null    float64
 8   Content Rating  10839 non-null  object
 9   Genres          10839 non-null  object
 10  Last Updated    10839 non-null  datetime64[ns]
 11  Current Ver     10831 non-null  object
 12  Android Ver     10837 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(2), object(7)
memory usage: 1.2+ MB

In [147]:
data_copy.to_csv("cleaned_googleplaystore_data",index=False)